# default configuration
baseURL = "https://asawari44.github.io/MyPortfolio/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Asawari Joshi"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

#[[menu.main]]
#URL = "blog"
#name = "Blog"
#weight = 2

[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 2

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 3


# default parameters
[params]
home = "Home"
logo = ""
# theme color
#theme_color = "#41228e"
theme_color = "#B19CD9"
# contact info
phone = "+358 417269091"
email = "asawari44@email.com"
address = "Kungshamra 41, 1219, Solna, Sweden. 170 70"
# meta description
author = "Asawari Joshi"
description = "Student at KTH Royal Institute of Technology, Sweden | Cloud and DevOps Engineer | Sr. Software Engineer | Automation Opportunist | Former DevOps intern @Aalto University, Finland | Master's degree in Cloud and Network Infrastructures"
# google analytics
google_analytics_id = "" # Your ID
# copyright
#copyright = "Copyright &copy; 2020 a theme by [gethugothemes](https://gethugothemes.com)"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "#" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"

# social site
[[params.social]]
icon = "ti-github"
URL = "https://github.com/asawari44"

#[[params.social]]
#icon = "ti-instagram"
#URL = "https://www.instagram.com/__chasing_illusions__/"

[[params.social]]
icon = "ti-linkedin"
URL = "https://www.linkedin.com/in/asawarijoshi/"

#[[params.social]]
#icon = "ti-twitter-alt"
#URL = "#"
